name: Deploy Dist Folder
# on: [push,workflow_dispatch]
on:
  push:
      branches: [main]
      paths-ignore: [README.md,".github/workflows/*"]
  workflow_dispatch:

jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository Code
              uses: actions/checkout@v4 
            - name: Setup nodejs & install Dependencies
              uses: ./.github/actions/setupnode
            - name: Run unit tests
              run: npm run test:unit
    build:
        needs: [test]
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repository Code
              uses: actions/checkout@v4 
              
            - name: Setup nodejs & install Dependencies
              uses: ./.github/actions/setupnode
            - name: Run unit tests
              
            - name: Build the project
              run: npm run build
            - name: Upload dist artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist-files
                  path: dist
    deploy:
        needs: [build]
        runs-on: ubuntu-latest
        steps: 
            - name: Download Dist artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist-files
                  path: dist
            - name: Deploy Dist
              run: |
                echo "Dist files:"
                ls -al dist
                echo "Deployement has been successfully completed!"

              
          
        