name: Greet User
on: push
jobs: 
    greet:
        runs-on: ubuntu-latest
        steps: 
            - name: greet user
              run: echo "Hello World!"
            - name: by user
              run: echo "Bye Bye!"